name: mynewpackage
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Najib-seeroo/package_test

environment:
  sdk: '>=3.4.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dynamic_fonts: ^2.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  speech_to_text: ^6.6.0
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  google_maps_place_picker:
     git:
      url: https://github.com/Najib-seeroo/place_picker
      ref: 0.0.2
  location: ^6.0.2
  maps_launcher: ^2.2.1
  permission_handler: ^11.3.1
  flutter_rating_bar: ^4.0.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.11


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/locales/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages