name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 3.0.1
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  google_api_headers: ^3.8.0
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  provider: ^6.0.5
  tuple: ^2.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

dependency_overrides:
  http: ^0.13.5

false_secrets:
 - /example/lib/keys.dart
 - /example/android/app/src/main/AndroidManifest.xml
 - /example/ios/Runner/AppDelegate.swift
